version: '3'

services:
  sonarqube:
    build: ./sonar
    ports:
      - 9000:9000
    networks:
      - sonar_network
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=s0narPassw0rd
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data

  sonar-db:
    image: postgres:latest
    networks:
      - sonar_network
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=s0narPassw0rd
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonar_network:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  postgresql:
  postgresql_data:
